{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-pro.redisHost" . }}
  labels:
    {{- include "sentinel-pro.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  selector:
    {{- include "sentinel-pro.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
