apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-pro.secretName" . }}
  labels:
    {{- include "sentinel-pro.labels" . | nindent 4 }}
type: Opaque
stringData:
  SENTINEL_DB_URL: {{ include "sentinel-pro.dbUrl" . | quote }}
  SENTINEL_REDIS_URL: {{ include "sentinel-pro.redisUrl" . | quote }}
  SENTINEL_CELERY_BROKER_URL: {{ include "sentinel-pro.redisUrl" . | quote }}
  SENTINEL_CELERY_RESULT_BACKEND: {{ include "sentinel-pro.redisResultBackend" . | quote }}
  SENTINEL_OAUTH_CLIENTS: {{ .Values.auth.oauthClients | quote }}
  SENTINEL_JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
