apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-pro.fullname" . }}-worker
  labels:
    {{- include "sentinel-pro.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "sentinel-pro.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "sentinel-pro.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - sentinel_pro.jobs.celery_app.celery_app
            - worker
            - --loglevel={{ .Values.config.logLevel }}
            - --concurrency={{ .Values.worker.concurrency }}
            - --queues={{ .Values.config.queueName }}
          envFrom:
            - configMapRef:
                name: {{ include "sentinel-pro.configName" . }}
            - secretRef:
                name: {{ include "sentinel-pro.secretName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
